/**
 * Boots eye shape scanner product catalog.
 * Source: data/boots-product-catalog.csv (Boots retailer rows only).
 * Regenerate: npm run catalog:generate
 * Pack shots: public/products/{SKU}.jpg
 */

import type { EyeShape } from "@/types/classification";

export interface BootsCatalogProduct {
  sku: string;
  name: string;
  isAll: boolean;
  eyeShapes: EyeShape[];
  tryOnUrl?: string;
  bootsUrl?: string;
}

export const BOOTS_PRODUCT_CATALOG: BootsCatalogProduct[] = [
  {
    sku: '6001204N',
    name: 'Naturals No.035',
    isAll: false,
    eyeShapes: ['almond', 'round', 'monolid'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=naturals&product=6001204N',
    bootsUrl: 'https://www.boots.com/eylure-lengthening-035-lashes-10172212',
  },
  {
    sku: '6001321N',
    name: 'Naturals No.031',
    isAll: false,
    eyeShapes: ['almond', 'round', 'monolid', 'upturned'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=naturals&product=6001321N',
    bootsUrl: 'https://www.boots.com/eylure-naturals-031-lashes-10172214',
  },
  {
    sku: '6001816N',
    name: '3/4 Length No.003',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=_3_4_length&product=6001816N',
    bootsUrl: 'https://www.boots.com/eylure-accent-lashes-003-10228136',
  },
  {
    sku: '6001817N',
    name: '3/4 Length No.005',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=_3_4_length&product=6001817N',
    bootsUrl: 'https://www.boots.com/eylure-accent-lashes-005-10228137',
  },
  {
    sku: '6001916N',
    name: 'Volume No.109',
    isAll: false,
    eyeShapes: ['round', 'almond', 'monolid'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=volume&product=6001916N',
    bootsUrl: 'https://www.boots.com/eylure-volume-lashes-109-10244810',
  },
  {
    sku: '6002418N',
    name: '3/4 Length No.008',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=_3_4_length&product=6002418N',
    bootsUrl: 'https://www.boots.com/Eylure-Fluttery-Light-008-False-Lashes-10276956',
  },
  {
    sku: '6002419N',
    name: 'Naturals No.022',
    isAll: false,
    eyeShapes: ['almond', 'round', 'monolid'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=naturals&product=6002419N',
    bootsUrl: 'https://www.boots.com/Eylure-Naturals-022-False-Lashes-10276957',
  },
  {
    sku: '70122K',
    name: '3/4 Length No.002',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=_3_4_length&product=70122K',
    bootsUrl: 'https://www.boots.com/eylure-3-quarter-length-002--10293360',
  },
  {
    sku: '70123K',
    name: '3/4 Length No.004',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=_3_4_length&product=70123K',
    bootsUrl: 'https://www.boots.com/eylure-3-quarter-length-004--10293361',
  },
  {
    sku: '70369K',
    name: 'Light & Wispy No.165',
    isAll: false,
    eyeShapes: ['almond', 'downturned', 'round', 'upturned'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=light_&_wispy&product=70369K',
    bootsUrl: 'https://www.boots.com/eylure-eylure-fluttery-light-no-165-lashes-10305749',
  },
  {
    sku: '70375K',
    name: '3/4 Length No.013',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=_3_4_length&product=70375K',
    bootsUrl: 'https://www.boots.com/eylure-3-4-length-no-013-lashes-10305753',
  },
  {
    sku: '70447K',
    name: 'Volume & Curl No.112',
    isAll: false,
    eyeShapes: ['downturned', 'hooded', 'almond'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=volume_&_curl&product=70447K',
    bootsUrl: 'https://www.boots.com/eylure-volume-no-112-extreme-curl-10316673',
  },
  {
    sku: '70462K',
    name: '3/4 Length No.014',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=_3_4_length&product=70462K',
    bootsUrl: 'https://www.boots.com/eylure-3-4-length-no-014-10316675',
  },
  {
    sku: '70469K',
    name: 'Faux Mink Clusters',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-fauxmink-individual-lashes-10327480',
  },
  {
    sku: '70495K',
    name: 'Volume & Curl No.114',
    isAll: false,
    eyeShapes: ['round', 'almond', 'monolid'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=volume_&_curl&product=70495K',
    bootsUrl: 'https://www.boots.com/eylure-volume-no-114-extreme-curl-10316674',
  },
  {
    sku: '70533K',
    name: 'Volume & Curl No.119',
    isAll: false,
    eyeShapes: ['round', 'almond', 'hooded', 'upturned'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=volume_&_curl&product=70533K',
    bootsUrl: 'https://www.boots.com/eylure-extreme-volume-119-extremecurl-10327478',
  },
  {
    sku: '70578K',
    name: '3/4 Length No.018',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=_3_4_length&product=70578K',
    bootsUrl: 'https://www.boots.com/eylure-three-quarter-length-lash-no-018-10331072',
  },
  {
    sku: '70613K',
    name: 'Full & Wispy No.184',
    isAll: false,
    eyeShapes: ['almond', 'hooded', 'downturned'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=full_&_wispy&product=70613K',
    bootsUrl: 'https://www.boots.com/eylure-shorter-lash-band-no-184-10331080',
  },
  {
    sku: '70629K',
    name: 'Volume & Curl Clusters',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-extreme-curl-clusters-10331077',
  },
  {
    sku: '70693K',
    name: '3/4 Length No.030',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=_3_4_length&product=70693K',
    bootsUrl: 'https://www.boots.com/eylure-34-length-030-10338121',
  },
  {
    sku: '70700K',
    name: 'Clusters- Volume',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-individuals---volume--10338123',
  },
  {
    sku: '70706K',
    name: 'Volume & Curl No.123',
    isAll: false,
    eyeShapes: ['round', 'almond', 'hooded', 'upturned'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=volume_&_curl&product=70706K',
    bootsUrl: 'https://www.boots.com/eylure-volume-and-curl-no123-10338126',
  },
  {
    sku: '70725K',
    name: 'Naturals No.032',
    isAll: false,
    eyeShapes: ['downturned', 'almond', 'hooded'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=naturals&product=70725K',
    bootsUrl: 'https://www.boots.com/eylure-naturals-no032-10338125',
  },
  {
    sku: '70763K',
    name: 'Light & Wispy No.162',
    isAll: false,
    eyeShapes: ['hooded', 'almond', 'downturned'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=light_&_wispy&product=70763K',
    bootsUrl: 'https://www.boots.com/eylure-light-and-wispy-lashes-no162-10345448',
  },
  {
    sku: '70764K',
    name: 'Light & Wispy No.160',
    isAll: false,
    eyeShapes: ['downturned', 'round', 'almond'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=light_&_wispy&product=70764K',
    bootsUrl: 'https://www.boots.com/eylure-light-and-wispy-lashes-no160--10345449',
  },
  {
    sku: '70772K',
    name: 'Clusters - Fluffy',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-clusters-fluffy-lashes-10345452',
  },
  {
    sku: '70773K',
    name: 'Clusters - Wispy',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-clusters-wispy-lashes-10345453',
  },
  {
    sku: '70786K',
    name: 'Naturals No.033',
    isAll: false,
    eyeShapes: ['almond', 'round', 'hooded', 'upturned'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=naturals&product=70786K',
    bootsUrl: 'https://www.boots.com/eylure-naturals-no-033-10345451',
  },
  {
    sku: '70794K',
    name: 'Underlash Natural Salon Curl Kit',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-underlash-natural-salon-curl-kit-1035456',
  },
  {
    sku: '70872K',
    name: '3/4 Length No.001',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=_3_4_length&product=70872K',
    bootsUrl: 'https://www.boots.com/webapp/wcs/stores/servlet/ProductDisplay',
  },
  {
    sku: '70873K',
    name: 'Brown/Black Cluster- Naturals No.5',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-brown-black-cluster-naturals-no5-and-lash-adhesive-1ml-10352681',
  },
  {
    sku: '70874K',
    name: 'Cluster Lash- Fluttery No.6',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-clusters-fluttery-no6-false-lashes-10352682',
  },
  {
    sku: '70875K',
    name: 'Faux Mink Clusters- Volume No.01',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-faux-mink-clusters-volume-01-false-lashes-pair-and-lash-adhesive-1ml-10352683',
  },
  {
    sku: '70876K',
    name: 'Half Lash No.5',
    isAll: false,
    eyeShapes: ['almond', 'round', 'monolid'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=half_lash&product=70876K',
    bootsUrl: 'https://www.boots.com/eylure-half-lash-no5-false-lashes-pair-and-lash-adhesive-1ml-10352568',
  },
  {
    sku: '70885K',
    name: 'Volume No. 098',
    isAll: false,
    eyeShapes: ['downturned', 'round', 'almond'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=volume&product=70885K',
    bootsUrl: 'https://www.boots.com/eylure-volume-lash-098-false-lashes-pair-and-lash-adhesive-1ml-10352689',
  },
  {
    sku: '70889K',
    name: 'Half Lash No.7',
    isAll: false,
    eyeShapes: ['downturned', 'hooded', 'almond'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=half_lash&product=70889K',
    bootsUrl: 'https://www.boots.com/eylure-half-lash-no7-false-lashes-pair-and-lash-adhesive-1ml-10352567',
  },
  {
    sku: '70906K',
    name: 'UL PG Natural Salon Curl Clusters',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-underlash-preglued-clusters-natural-false-lashes-10352686',
  },
  {
    sku: '70916K',
    name: 'Half lash No.3',
    isAll: false,
    eyeShapes: ['downturned', 'hooded', 'almond'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=half_lash&product=70916K',
    bootsUrl: 'https://www.boots.com/eylure-half-lash-no-3-10365292',
  },
  {
    sku: '70918K',
    name: 'Naturals No.039',
    isAll: false,
    eyeShapes: ['almond', 'round', 'monolid'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=naturals&product=70918K',
    bootsUrl: 'https://www.boots.com/eylure-naturals-no-039-10365293',
  },
  {
    sku: '70919K',
    name: 'Full & Wispy No.187',
    isAll: false,
    eyeShapes: ['almond', 'hooded', 'downturned'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=full_&_wispy&product=70919K',
    bootsUrl: 'https://www.boots.com/eylure-fully-and-wispy-no-187-10365291',
  },
  {
    sku: '70922K',
    name: 'Cluster-Flutter No.4',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-clusters-flutter-no-4-10365289',
  },
  {
    sku: '70923K',
    name: 'Cluster- Dramatic No.12',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-clusters-dramatic-no-12-10365288',
  },
  {
    sku: '70957K',
    name: 'Faux Mink- Emerald',
    isAll: false,
    eyeShapes: ['almond', 'hooded', 'downturned'],
    tryOnUrl: 'https://www.eylure.co.uk/try-on/?range=faux_mink&product=70957K',
    bootsUrl: 'https://www.boots.com/eylure-faux-mink-emerald--10365290',
  },
  {
    sku: '71007K',
    name: 'Half Lash No.4',
    isAll: false,
    eyeShapes: ['almond', 'round', 'upturned'],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-half-lash-no-4-10373940',
  },
  {
    sku: '71014K',
    name: '3/4 Length No.016',
    isAll: false,
    eyeShapes: ['round', 'almond', 'hooded', 'upturned'],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-3-4-length-no-016-lashes-10373946',
  },
  {
    sku: '71019K',
    name: 'Light & Wispy No.172',
    isAll: false,
    eyeShapes: ['almond', 'round', 'upturned'],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-light-and-wispy-no-172-cat-eye-lashes-10373944',
  },
  {
    sku: '71026K',
    name: 'Light & Fluffy No.250',
    isAll: false,
    eyeShapes: ['downturned', 'almond', 'hooded', 'round', 'monolid'],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-light-and-fluffy-no-250-lashes-10373942',
  },
  {
    sku: '71031K',
    name: 'Clusters- Soft & Fluffy No.26',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-clusters-soft-and-fluffy-no-26-lashes-10373938',
  },
  {
    sku: '71033K',
    name: 'Clusters- Wet look No.30',
    isAll: true,
    eyeShapes: [],
    tryOnUrl: undefined,
    bootsUrl: 'https://www.boots.com/eylure-clusters-wet-look-no-30-lashes-10373948',
  },
];
